package pe.edu.upn.encuesta.entidad;

// Generated 02/12/2016 05:39:11 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import com.indra.core.domain.Entidad;

/**
 * DetalleClienteSectorizado generated by hbm2java
 */
public class DetalleClienteSectorizado extends Entidad {

    private static final long serialVersionUID = 1L;
    private BigDecimal jobInstanceId;
    private String fechaMovimiento;
    private String cuentaContable;
    private BigDecimal saldoMonedaNacional;
    private String origen;
    private String divisa;
    private String codigoSector;
    private String codigoCentral;
    private String tipoDocumento;
    private String numeroDocumento;
    private String nombres;
    private String corasu;
    private String pecnares;
    private String ciiu;
    private Date periodo;

    public BigDecimal getJobInstanceId() {
        return this.jobInstanceId;
    }

    public void setJobInstanceId(BigDecimal jobInstanceId) {
        this.jobInstanceId = jobInstanceId;
    }

    public String getFechaMovimiento() {
        return this.fechaMovimiento;
    }

    public void setFechaMovimiento(String fechaMovimiento) {
        this.fechaMovimiento = fechaMovimiento;
    }

    public String getCuentaContable() {
        return this.cuentaContable;
    }

    public void setCuentaContable(String cuentaContable) {
        this.cuentaContable = cuentaContable;
    }

    public BigDecimal getSaldoMonedaNacional() {
        return this.saldoMonedaNacional;
    }

    public void setSaldoMonedaNacional(BigDecimal saldoMonedaNacional) {
        this.saldoMonedaNacional = saldoMonedaNacional;
    }

    public String getOrigen() {
        return this.origen;
    }

    public void setOrigen(String origen) {
        this.origen = origen;
    }

    public String getDivisa() {
        return this.divisa;
    }

    public void setDivisa(String divisa) {
        this.divisa = divisa;
    }

    public String getCodigoSector() {
        return this.codigoSector;
    }

    public void setCodigoSector(String codigoSector) {
        this.codigoSector = codigoSector;
    }

    public String getCodigoCentral() {
        return this.codigoCentral;
    }

    public void setCodigoCentral(String codigoCentral) {
        this.codigoCentral = codigoCentral;
    }

    public String getTipoDocumento() {
        return this.tipoDocumento;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }

    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getCorasu() {
        return this.corasu;
    }

    public void setCorasu(String corasu) {
        this.corasu = corasu;
    }

    public String getPecnares() {
        return this.pecnares;
    }

    public void setPecnares(String pecnares) {
        this.pecnares = pecnares;
    }

    public String getCiiu() {
        return this.ciiu;
    }

    public void setCiiu(String ciiu) {
        this.ciiu = ciiu;
    }

    public Date getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(Date periodo) {
        this.periodo = periodo;
    }

}
