package pe.edu.upn.encuesta.entidad;
// Generated 14/02/2018 06:34:20 AM by Hibernate Tools 4.3.1

import com.indra.core.domain.Entidad;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EncuestaRespuesta generated by hbm2java
 */
public class EncuestaRespuesta extends Entidad {

    private Integer idEncuestaResultado;
    private Encuesta encuesta;
    private Persona persona;
    private Date fechaRegistro;
    private Set preguntaRespuestas = new HashSet(0);

    public EncuestaRespuesta() {
    }

    public EncuestaRespuesta(Encuesta encuesta, Persona persona) {
        this.encuesta = encuesta;
        this.persona = persona;
    }

    public EncuestaRespuesta(Encuesta encuesta, Persona persona, Date fechaRegistro, Set preguntaRespuestas) {
        this.encuesta = encuesta;
        this.persona = persona;
        this.fechaRegistro = fechaRegistro;
        this.preguntaRespuestas = preguntaRespuestas;
    }

    public Integer getIdEncuestaResultado() {
        return this.idEncuestaResultado;
    }

    public void setIdEncuestaResultado(Integer idEncuestaResultado) {
        this.idEncuestaResultado = idEncuestaResultado;
    }

    public Encuesta getEncuesta() {
        return this.encuesta;
    }

    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }

    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public Set getPreguntaRespuestas() {
        return this.preguntaRespuestas;
    }

    public void setPreguntaRespuestas(Set preguntaRespuestas) {
        this.preguntaRespuestas = preguntaRespuestas;
    }

}
