package pe.edu.upn.encuesta.entidad;
// Generated 14/02/2018 06:34:20 AM by Hibernate Tools 4.3.1

import com.indra.core.domain.Entidad;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Encuesta generated by hbm2java
 */
public class Encuesta extends Entidad {

    private Integer idEncuesta;
    private Inquilino inquilino;
    private String nombre;
    private Date fechaInicio;
    private Date fechaFin;
    private Integer duracion;
    private String clave;
    private Set preguntas = new HashSet(0);
    private Set encuestaRespuestas = new HashSet(0);

    public Encuesta() {
    }

    public Encuesta(Inquilino inquilino) {
        this.inquilino = inquilino;
    }

    public Encuesta(Inquilino inquilino, String nombre, Date fechaInicio, Date fechaFin, Integer duracion, String clave, Set preguntas, Set encuestaRespuestas) {
        this.inquilino = inquilino;
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.duracion = duracion;
        this.clave = clave;
        this.preguntas = preguntas;
        this.encuestaRespuestas = encuestaRespuestas;
    }

    public Integer getIdEncuesta() {
        return this.idEncuesta;
    }

    public void setIdEncuesta(Integer idEncuesta) {
        this.idEncuesta = idEncuesta;
    }

    public Inquilino getInquilino() {
        return this.inquilino;
    }

    public void setInquilino(Inquilino inquilino) {
        this.inquilino = inquilino;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    public Integer getDuracion() {
        return this.duracion;
    }

    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }

    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public Set getPreguntas() {
        return this.preguntas;
    }

    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }

    public Set getEncuestaRespuestas() {
        return this.encuestaRespuestas;
    }

    public void setEncuestaRespuestas(Set encuestaRespuestas) {
        this.encuestaRespuestas = encuestaRespuestas;
    }

}
