package pe.edu.upn.encuesta.entidad;
// Generated 14/02/2018 06:34:20 AM by Hibernate Tools 4.3.1

import com.indra.core.domain.Entidad;
import java.util.HashSet;
import java.util.Set;

/**
 * Inquilino generated by hbm2java
 */
public class Inquilino extends Entidad {

    private Integer idInquilino;
    private String nombre;
    private String ruc;
    private String direccion;
    private String logo;
    private String tema;
    private Set encuestas = new HashSet(0);

    public Inquilino() {
    }

    public Inquilino(String nombre, String ruc, String direccion, String logo, String tema, Set encuestas) {
        this.nombre = nombre;
        this.ruc = ruc;
        this.direccion = direccion;
        this.logo = logo;
        this.tema = tema;
        this.encuestas = encuestas;
    }

    public Integer getIdInquilino() {
        return this.idInquilino;
    }

    public void setIdInquilino(Integer idInquilino) {
        this.idInquilino = idInquilino;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getRuc() {
        return this.ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getTema() {
        return this.tema;
    }

    public void setTema(String tema) {
        this.tema = tema;
    }

    public Set getEncuestas() {
        return this.encuestas;
    }

    public void setEncuestas(Set encuestas) {
        this.encuestas = encuestas;
    }

}
