package pe.edu.upn.encuesta.entidad;

// Generated 02/12/2016 05:39:11 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import com.indra.core.domain.Entidad;

/**
 * OtrosDisponiblesRestringidos generated by hbm2java
 */
public class OtrosDisponiblesRestringidos extends Entidad {

    private static final long serialVersionUID = 1L;
    private BigDecimal jobInstanceId;
    private BigDecimal codigo;
    private String nombreUnidad;
    private Date fecha;
    private String caso;
    private String abogado;
    private String cuentaContable;
    private BigDecimal importe;
    private String situacion;
    private String documentoIdentidad;
    private Date periodo;

    public BigDecimal getJobInstanceId() {
        return this.jobInstanceId;
    }

    public void setJobInstanceId(BigDecimal jobInstanceId) {
        this.jobInstanceId = jobInstanceId;
    }

    public BigDecimal getCodigo() {
        return this.codigo;
    }

    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }

    public String getNombreUnidad() {
        return this.nombreUnidad;
    }

    public void setNombreUnidad(String nombreUnidad) {
        this.nombreUnidad = nombreUnidad;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getCaso() {
        return this.caso;
    }

    public void setCaso(String caso) {
        this.caso = caso;
    }

    public String getAbogado() {
        return this.abogado;
    }

    public void setAbogado(String abogado) {
        this.abogado = abogado;
    }

    public String getCuentaContable() {
        return this.cuentaContable;
    }

    public void setCuentaContable(String cuentaContable) {
        this.cuentaContable = cuentaContable;
    }

    public BigDecimal getImporte() {
        return this.importe;
    }

    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

    public String getSituacion() {
        return this.situacion;
    }

    public void setSituacion(String situacion) {
        this.situacion = situacion;
    }

    public String getDocumentoIdentidad() {
        return this.documentoIdentidad;
    }

    public void setDocumentoIdentidad(String documentoIdentidad) {
        this.documentoIdentidad = documentoIdentidad;
    }

    public Date getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(Date periodo) {
        this.periodo = periodo;
    }

}
