package pe.edu.upn.encuesta.entidad;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.indra.core.domain.Entidad;

/**
 * Parametro generated by hbm2java
 */
public class Parametro extends Entidad {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Long idParametroPadre;
    private Parametro parametro;
    private Long tipo;
    private String nombre;
    private String descripcion;
    private String codigo;
    private String codigoEti;
    private char codigoHabil;
    private Long entero;
    private String enteroEti;
    private char enteroHabil;
    private BigDecimal decimales;
    private String decimalesEti;
    private char decimalesHabil;
    private String texto;
    private String textoEti;
    private char textoHabil;
    private String texto2;
    private String textoEti2;
    private char textoHabil2;
    private String texto3;
    private String textoEti3;
    private char textoHabil3;
    private String texto4;
    private String textoEti4;
    private char textoHabil4;
    private Date fecha;
    private String fechaEti;
    private char fechaHabil;
    private String hora;
    private String horaEti;
    private char horaHabil;
    private Character booleano;
    private String booleanoEti;
    private char booleanoHabil;
    private Character booleano2;
    private String booleanoEti2;
    private char booleanoHabil2;
    private String funcion;
    private String funcionEti;
    private char funcionHabil;
    private String funcionMsg;
    private Character permiteHijo;
    @JsonIgnore
    private List<Parametro> parametros = new ArrayList<Parametro>();
    @JsonIgnore
    private Parametro parametroTipo;
    private String validarCodigo;
    private String permiteEliminar;
    @JsonIgnore
    private String blobVal;
    @JsonIgnore
    private String blobEti;
    
    private Character blobHabil;

    private Long indice;

    public String getNombreTipo() {
        return getParametroTipo().getNombre();
    }

    public String getNombrePadre() {
        return getParametro().getNombre();
    }

    public Long getParametroId() {
        return getParametro().getId();
    }

    public String getEstadoDescripcion() {
        return getEstado() == null ? ""
                : "A".equalsIgnoreCase(getEstado()) ? "Activo" 
                : "I".equalsIgnoreCase(getEstado()) ? "Inactivo"
                : "No registrado";
    }

    @JsonIgnore
    public Parametro getParametro() {
        if (parametro == null) {
            parametro = new Parametro();
        }
        return parametro;
    }

    @JsonProperty
    public void setParametro(Parametro parametro) {
        this.parametro = parametro;
        if(parametro != null) {
            this.idParametroPadre = parametro.getId();
        }
    }

    public Long getTipo() {
        return tipo;
    }

    public void setTipo(Long tipo) {
        this.tipo = tipo;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigoEti() {
        return codigoEti;
    }

    public void setCodigoEti(String codigoEti) {
        this.codigoEti = codigoEti;
    }

    public char getCodigoHabil() {
        return codigoHabil;
    }

    public void setCodigoHabil(char codigoHabil) {
        this.codigoHabil = codigoHabil;
    }

    public Long getEntero() {
        return entero;
    }

    public void setEntero(Long entero) {
        this.entero = entero;
    }

    public String getEnteroEti() {
        return enteroEti;
    }

    public void setEnteroEti(String enteroEti) {
        this.enteroEti = enteroEti;
    }

    public char getEnteroHabil() {
        return enteroHabil;
    }

    public void setEnteroHabil(char enteroHabil) {
        this.enteroHabil = enteroHabil;
    }

    public BigDecimal getDecimales() {
        return decimales;
    }

    public void setDecimales(BigDecimal decimales) {
        this.decimales = decimales;
    }

    public String getDecimalesEti() {
        return decimalesEti;
    }

    public void setDecimalesEti(String decimalesEti) {
        this.decimalesEti = decimalesEti;
    }

    public char getDecimalesHabil() {
        return decimalesHabil;
    }

    public void setDecimalesHabil(char decimalesHabil) {
        this.decimalesHabil = decimalesHabil;
    }

    public String getTexto() {
        return texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public String getTextoEti() {
        return textoEti;
    }

    public void setTextoEti(String textoEti) {
        this.textoEti = textoEti;
    }

    public char getTextoHabil() {
        return textoHabil;
    }

    public void setTextoHabil(char textoHabil) {
        this.textoHabil = textoHabil;
    }

    public String getTexto2() {
        return texto2;
    }

    public void setTexto2(String texto2) {
        this.texto2 = texto2;
    }

    public String getTextoEti2() {
        return textoEti2;
    }

    public void setTextoEti2(String textoEti2) {
        this.textoEti2 = textoEti2;
    }

    public char getTextoHabil2() {
        return textoHabil2;
    }

    public void setTextoHabil2(char textoHabil2) {
        this.textoHabil2 = textoHabil2;
    }

    public String getTexto3() {
        return texto3;
    }

    public void setTexto3(String texto3) {
        this.texto3 = texto3;
    }

    public String getTextoEti3() {
        return textoEti3;
    }

    public void setTextoEti3(String textoEti3) {
        this.textoEti3 = textoEti3;
    }

    public char getTextoHabil3() {
        return textoHabil3;
    }

    public void setTextoHabil3(char textoHabil3) {
        this.textoHabil3 = textoHabil3;
    }

    public String getTexto4() {
        return texto4;
    }

    public void setTexto4(String texto4) {
        this.texto4 = texto4;
    }

    public String getTextoEti4() {
        return textoEti4;
    }

    public void setTextoEti4(String textoEti4) {
        this.textoEti4 = textoEti4;
    }

    public char getTextoHabil4() {
        return textoHabil4;
    }

    public void setTextoHabil4(char textoHabil4) {
        this.textoHabil4 = textoHabil4;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getFechaEti() {
        return fechaEti;
    }

    public void setFechaEti(String fechaEti) {
        this.fechaEti = fechaEti;
    }

    public char getFechaHabil() {
        return fechaHabil;
    }

    public void setFechaHabil(char fechaHabil) {
        this.fechaHabil = fechaHabil;
    }

    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }

    public String getHoraEti() {
        return horaEti;
    }

    public void setHoraEti(String horaEti) {
        this.horaEti = horaEti;
    }

    public char getHoraHabil() {
        return horaHabil;
    }

    public void setHoraHabil(char horaHabil) {
        this.horaHabil = horaHabil;
    }

    public Character getBooleano() {
        return booleano;
    }

    public void setBooleano(Character booleano) {
        this.booleano = booleano;
    }

    public String getBooleanoEti() {
        return booleanoEti;
    }

    public void setBooleanoEti(String booleanoEti) {
        this.booleanoEti = booleanoEti;
    }

    public char getBooleanoHabil() {
        return booleanoHabil;
    }

    public void setBooleanoHabil(char booleanoHabil) {
        this.booleanoHabil = booleanoHabil;
    }

    public Character getBooleano2() {
        return booleano2;
    }

    public void setBooleano2(Character booleano2) {
        this.booleano2 = booleano2;
    }

    public String getBooleanoEti2() {
        return booleanoEti2;
    }

    public void setBooleanoEti2(String booleanoEti2) {
        this.booleanoEti2 = booleanoEti2;
    }

    public char getBooleanoHabil2() {
        return booleanoHabil2;
    }

    public void setBooleanoHabil2(char booleanoHabil2) {
        this.booleanoHabil2 = booleanoHabil2;
    }

    public String getFuncion() {
        return funcion;
    }

    public void setFuncion(String funcion) {
        this.funcion = funcion;
    }

    public String getFuncionEti() {
        return funcionEti;
    }

    public void setFuncionEti(String funcionEti) {
        this.funcionEti = funcionEti;
    }

    public char getFuncionHabil() {
        return funcionHabil;
    }

    public void setFuncionHabil(char funcionHabil) {
        this.funcionHabil = funcionHabil;
    }

    public String getFuncionMsg() {
        return funcionMsg;
    }

    public void setFuncionMsg(String funcionMsg) {
        this.funcionMsg = funcionMsg;
    }

    public Character getPermiteHijo() {
        return permiteHijo;
    }

    public void setPermiteHijo(Character permiteHijo) {
        this.permiteHijo = permiteHijo;
    }

    public List<Parametro> getParametros() {
        return parametros;
    }

    public void setParametros(List<Parametro> parametros) {
        this.parametros = parametros;
    }

    public Parametro getParametroTipo() {
        if (parametroTipo == null) {
            parametroTipo = new Parametro();
        }
        return parametroTipo;
    }

    public void setParametroTipo(Parametro parametroTipo) {
        this.parametroTipo = parametroTipo;
    }

    public String getValidarCodigo() {
        if (validarCodigo == null) {
            validarCodigo = "N";
        }
        return validarCodigo;
    }

    public void setValidarCodigo(String validarCodigo) {
        this.validarCodigo = validarCodigo;
    }

    public String getPermiteEliminar() {
        return permiteEliminar;
    }

    public void setPermiteEliminar(String permiteEliminar) {
        this.permiteEliminar = permiteEliminar;
    }

    public String getBlobEti() {
        return blobEti;
    }

    public void setBlobEti(String blobEti) {
        this.blobEti = blobEti;
    }

    public Character getBlobHabil() {
        return blobHabil;
    }

    public void setBlobHabil(Character blobHabil) {
        this.blobHabil = blobHabil;
    }

    public String getBlobVal() {
        return blobVal;
    }

    public void setBlobVal(String blobVal) {
        this.blobVal = blobVal;
    }

    public Long getIndice() {
        return indice;
    }

    public void setIndice(Long indice) {
        this.indice = indice;
    }

    public Long getIdParametroPadre() {
        return idParametroPadre;
    }

    public void setIdParametroPadre(Long idParametroPadre) {
        this.idParametroPadre = idParametroPadre;
    }

}
