package pe.edu.upn.encuesta.entidad;
// Generated 14/02/2018 06:34:20 AM by Hibernate Tools 4.3.1

import com.indra.core.domain.Entidad;

/**
 * PreguntaRespuesta generated by hbm2java
 */
public class PreguntaRespuesta extends Entidad {

    private Integer idPreguntaRespuesta;
    private EncuestaRespuesta encuestaRespuesta;
    private Pregunta pregunta;
    private String respuesta;

    public PreguntaRespuesta() {
    }

    public PreguntaRespuesta(EncuestaRespuesta encuestaRespuesta, Pregunta pregunta) {
        this.encuestaRespuesta = encuestaRespuesta;
        this.pregunta = pregunta;
    }

    public PreguntaRespuesta(EncuestaRespuesta encuestaRespuesta, Pregunta pregunta, String respuesta) {
        this.encuestaRespuesta = encuestaRespuesta;
        this.pregunta = pregunta;
        this.respuesta = respuesta;
    }

    public Integer getIdPreguntaRespuesta() {
        return this.idPreguntaRespuesta;
    }

    public void setIdPreguntaRespuesta(Integer idPreguntaRespuesta) {
        this.idPreguntaRespuesta = idPreguntaRespuesta;
    }

    public EncuestaRespuesta getEncuestaRespuesta() {
        return this.encuestaRespuesta;
    }

    public void setEncuestaRespuesta(EncuestaRespuesta encuestaRespuesta) {
        this.encuestaRespuesta = encuestaRespuesta;
    }

    public Pregunta getPregunta() {
        return this.pregunta;
    }

    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }

    public String getRespuesta() {
        return this.respuesta;
    }

    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

}
