package pe.edu.upn.encuesta.entidad;

// Generated 02/12/2016 05:39:11 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import com.indra.core.domain.Entidad;

/**
 * SaldoDiario generated by hbm2java
 */
public class SaldoDiario extends Entidad {

    private static final long serialVersionUID = 1L;
    private BigDecimal jobInstanceId;
    private String cuentaContable;
    private String descripcionCuentaContable;
    private BigDecimal saldoCuenta;
    private Character indicadorDetalle;
    private Date periodo;
    
    public BigDecimal getJobInstanceId() {
        return this.jobInstanceId;
    }

    public void setJobInstanceId(BigDecimal jobInstanceId) {
        this.jobInstanceId = jobInstanceId;
    }

    public String getCuentaContable() {
        return this.cuentaContable;
    }

    public void setCuentaContable(String cuentaContable) {
        this.cuentaContable = cuentaContable;
    }

    public String getDescripcionCuentaContable() {
        return this.descripcionCuentaContable;
    }

    public void setDescripcionCuentaContable(String descripcionCuentaContable) {
        this.descripcionCuentaContable = descripcionCuentaContable;
    }

    public BigDecimal getSaldoCuenta() {
        return this.saldoCuenta;
    }

    public void setSaldoCuenta(BigDecimal saldoCuenta) {
        this.saldoCuenta = saldoCuenta;
    }
    
    public Character getIndicadorDetalle() {
		return indicadorDetalle;
	}

	public void setIndicadorDetalle(Character indicadorDetalle) {
		this.indicadorDetalle = indicadorDetalle;
	}

	public Date getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(Date periodo) {
        this.periodo = periodo;
    }

}
