package pe.edu.upn.encuesta.entidad;
// Generated 14/02/2018 06:34:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoControl generated by hbm2java
 */
public class TipoControl  implements java.io.Serializable {


     private Integer idTipoControl;
     private String descripcion;
     private Set preguntas = new HashSet(0);

    public TipoControl() {
    }

    public TipoControl(String descripcion, Set preguntas) {
       this.descripcion = descripcion;
       this.preguntas = preguntas;
    }
   
    public Integer getIdTipoControl() {
        return this.idTipoControl;
    }
    
    public void setIdTipoControl(Integer idTipoControl) {
        this.idTipoControl = idTipoControl;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }




}


